# Generated by Django 5.0.1 on 2024-01-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
